name: Update Website
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  updatereadme:
    name: Update webpage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mv README.md moth.md
      - run: git pull
      - uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: './moth.md'
          destination_repo: 'StellarWitch7/stellarwitch7.github.io'
          destination_folder: './markdown/'
          user_email: '131844170+StellarWitch7@users.noreply.github.com'
          user_name: 'StellarWitch7'
          commit_message: 'Updated moth.md from https://github.com/StellarWitch7/Moth'
